### ISSUE TITLE
Get docker-compose working on CentOS server

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#109]
At the moment, the `docker-compose` command fails on the server. Without it, we need to do a lot of manual work to get the processes up and running.

**Comment by c-lliope** [comment]
[wrong issue]

**Comment by c-lliope** [comment]
Commands run to start a fresh instance, when no docker containers are running:

``` bash
sudo docker run --rm -e DB_HOST=db -e DB_USER=postgres -l db -v /crisisresponse:/app crisis_web ./bin/rake db:create db:migrate
sudo docker run --rm -e DB_HOST=db -e DB_USER=postgres -l db -v /crisisresponse:/app crisis_web ./bin/rake db:seed
sudo docker run --name crisisresponse_web -e DB_HOST=db -e DB_USER=postgres -p 80:3000 -l db -v /crisisresponse:/app crisis_web ./bin/serve
```

**Comment by c-lliope** [comment]
I tried to re-install `docker-compose` on our server, and in the process discovered a few new things:
1. We're getting the same errors with the newly installed version as we were with the old one. Those errors are:

``` bash
[wrightgb@local crisisresponse]$ docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is i                                                      t running?
[wrightgb@local crisisresponse]$ sudo /usr/local/bin/docker-compose up
[sudo] password for wrightgb:
Creating network "crisisresponse_default" with the default driver
ERROR: 404 page not found
```

The first error only appeared when using `docker-compose` without `sudo`. It seems that the user `wrightgb` probably doesn't have access to the `/var/run/docker.sock` file that docker is listening on. When `docker-compose` tries to connect to that socket, it's rejected and fails.

I was able to get around this error by making Docker listen to a TCP port as well as the unix socket, as suggested at https://github.com/docker/compose/issues/88#issuecomment-51583724. On our system, we need to run:

``` bash
 sudo docker daemon -H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock
```

After that, we can connect to the docker server with:

``` bash
$ export DOCKER_HOST=tcp://localhost:4243
$ docker-compose up
```

This, however, only gets us back to the second error:

```
[wrightgb@local crisisresponse]$ export DOCKER_HOST=tcp://localhost:4243
[wrightgb@local crisisresponse]$ echo $DOCKER_HOST
tcp://localhost:4243
[wrightgb@local crisisresponse]$ docker-compose up
Creating network "crisisresponse_default" with the default driver
ERROR: 404 page not found
```

So it appears that all of that work is unnecessary if we're comfortable just running `docker-compose` under `sudo`. It also means that the real problem preventing us from moving forward is the second one, `404 page not found`.

According to https://github.com/docker/compose/issues/3312, this error can be caused when the docker engine version is less than the client program requires. We can get more information with the `--verbose` flag:

``` bash
[wrightgb@local crisisresponse]$ docker-compose --verbose up
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.auth.auth.load_config: File doesn't exist
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 58, in main
  File "compose/cli/main.py", line 106, in perform_command
  File "compose/cli/command.py", line 34, in project_from_options
  File "compose/cli/command.py", line 79, in get_project
  File "compose/cli/command.py", line 55, in get_client
  File ".tox/py27/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
  File ".tox/py27/lib/python2.7/site-packages/docker/client.py", line 158, in _result
  File ".tox/py27/lib/python2.7/site-packages/docker/client.py", line 154, in _raise_for_status
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version                              : 1.22, server API version: 1.20)")
docker-compose returned -1
```

It looks like we'll either need to install the newer version of docker engine on our device, or downgrade our version of `docker-compose` to fit the `docker-engine` we have installed.

**Comment by c-lliope** [comment]
I improved our stopgap solution to a more effective startup script, stored at `bin/serveprod`.

The top lines stop the existing server container and start a new one. The commented-out lines at the bottom are useful references for starting the db container, running migrations, etc.

``` bash
sudo docker stop crisisresponse_web
sudo docker rm crisisresponse_web
sudo rm tmp/pids/server.pid
sudo docker run \
        --name crisisresponse_web \
        -p 80:3000 \
        -v /crisisresponse:/app \
        -l db \
        -e DB_HOST=db \
        -d crisis_web \
        ./bin/serve

# sudo docker run --name db -p 5432:5432 -d postgres
# sudo docker run --rm -v /crisisresponse:/app -l db -e DB_HOST=db -e DB_USER=postgres -it crisis_web ./bin/rake db:create db:migrate db:seed
# sudo docker run --name crisisresponse_web -p 80:3000 -v /crisisresponse:/app -d -l db -e DB_HOST=db -e DB_USER=postgres -it crisis_web ./bin/serve
```

**Comment by graysonwright** [comment]
@antislice – I've been leaving this issue open because it's been a good place for me to dump notes and documentation. Most of this is now included in the README, but you should read over it and make sure there's not additional useful information in here before you close it.

**Comment by antislice** [comment]
This issue was moved to getridealong/crisisresponse#134
