### ISSUE TITLE
How do we set up an effective dev environment on the SPD server?

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#12]
If we're developing directly on the SPD server, we should have an environment set up with all the tools we need to develop effectively. In case we need to abandon our server in favor of another, our environment set up should be easily portable to another machine.

An obvious solution is to package up all the development tools we need into a docker image, and do most or all of our work from inside the image. For example, we could install vim or neoVim for editing text files, then map the filesystem from our server into the development docker image. Any changes we make to files using the dev docker image would be reflected in the host filesystem.

Basic needs for a development environment:
- Vim or NeoVim
- Ruby
- Bash or Zsh
- Docker (docker-in-docker?)
- `wget` and/or `curl`
- `git`

Nice-to-have:
- [jq](https://robots.thoughtbot.com/jq-is-sed-for-json)
- [personal dotfiles](https://github.com/graysonwright/dotfiles)
- `tree`
- [The Silver Searcher](https://github.com/ggreer/the_silver_searcher)
- `tmux`

In addition, there will be packages and tools that we will need to use that are more appropriately stored with the application codebase than in a general development image. These include project-specific dependencies including Rails, postgres, necessary gems, etc.

The application-specific image will be defined in [this project's Dockerfile]. A general development image will be made available in [my personal Dockerfiles repository](https://github.com/graysonwright/dockerfiles).

[this project's Dockerfile](https://github.com/codeforamerica/crisisresponse/blob/master/Dockerfile)

**Comment by c-lliope** [comment]
Irrelevant – we decided to develop on our local machines and only use the remote servers for deployment. See https://github.com/codeforamerica/crisisresponse/issues/9
