### ISSUE TITLE
[RESEARCH] Port to ASP.net

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#126]
According to Michael Mattmiller, the Seattle IT department's application team mostly uses ASP.net. Supporting a Ruby on Rails application would likely be very difficult for them, and they'd need to adjust their team and infrastructure to support it.

This issue is an investigation into the feasibility of porting our application to ASP.net, in order to improve its chances of being sustained beyond the fellowship year.
## Open Questions
- [ ] General development
  - [x] Routing to controllers
  - [x] Passing data from controllers to views
  - [x] Serving HTML
  - [x] Serving CSS
  - [x] Serving JavaScript
  - [x] Importing data from CSV
  - [x] Creating data models
  - [ ] running custom SQL queries (likely required for fuzzy name searching)
  - [ ] Email: it looks like the `System.Net.Mail` library that is present in previous versions of ASP.net is not supported in vNext. Our best bet is likely [MailKit](https://github.com/jstedfast/MailKit).
- [ ] OSX development
  - [x] Running the server
  - [ ] running tests
  - [ ] running scaffold generators
  - [ ] running migrations
  - [ ] creating migrations from a class definition
  - [ ] persisting data locally
    - So far, haven't been able to get the SQLite adapter working on the mac
    - Currently installing SQL on a VM on the mac
    - Haven't tried the in-memory data store on the mac
- [ ] Windows development
  - Currently installing Visual Studio on the SPD laptop
  - [ ] Running the server
  - [ ] running tests
  - [ ] running scaffold generators
  - [ ] running migrations
  - [ ] creating migrations from a class definition
  - [ ] persisting data locally

**Comment by c-lliope** [comment]
Current tabs I have open during my investigation into sending mail with ASP.net:

https://github.com/jstedfast/MailKit/issues/291
https://hub.docker.com/r/namshi/smtp/
https://duckduckgo.com/?q=dotnet+osx+mailkit+send+from+localhost
http://www.pinfaq.com/90/how-test-dot-net-smtpclient-email-functionality-localhost
http://stackoverflow.com/questions/33000474/asp-5-mvc-6-sending-email
https://mailgun.com/app/domains/graysonwright.com/credentials?page=1
https://documentation.mailgun.com/quickstart-sending.html#send-via-smtp
http://ubuntuforums.org/showthread.php?t=1841740
http://blog.worldofcoding.com/2014/08/tlsexception-on-mono.html

https://discussions.apple.com/thread/2092900?start=0&tstart=0
https://stackoverflow.com/questions/8260858/how-to-send-email-from-terminal#
http://hints.macworld.com/article.php?story=20081217161612647

A good possible next step might be loading up everything I need to run a command-line dotnet application into Docker, shipping an image over to CentOS, and testing out MailKit on our server, using the smtp relay. The feedback time on that would be a bit rough, but it should be fairly straightforward.

**Comment by graysonwright** [comment]
This is no longer applicable – the application is written in Ruby on Rails, and there is no business or technical reason to port it over to ASP.net. If / When the application is moved off-prem to the cloud, there will be even less of a worry about which language it's written in. Closing.
