### ISSUE TITLE
Update "Day/Night" night mode button to "Night mode"

### ISSUE THREAD

**Issue by meredithhitchcock** [codeforamerica/crisisresponse#151]
Officers were confused about what "Day/Night" meant in usability testing. I'd change the language back to the original from the mocks, with "Night mode" or "Night mode: on/off"

**Comment by graysonwright** [comment]
I think this was resolved - we changed it to a toggle for "Light / Dark". I'm closing it for now.

CC @meredithhitchcock - Is there more work to be done on this? If so, feel free to reopen.
