### ISSUE TITLE
Change Management Proposal

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#290]
## Description of Change

We have built the RideAlong Response application to help the Crisis Response Team share information about people with mental illnesses or chemical dependencies with patrol officers.

Since February, we have designed, developed and tested this application with input and feedback from twenty field testers including bike patrol officers from the East and West precincts and car patrol officers from all five precincts.

We have prepared two additional servers – QA and production – to host our application.  We will expand access to our application beyond our field testers, to all SPD patrol officers.

## Reason for Change

This application is part of the plan for Consent Decree compliance.  When officers have access to better information about people in crisis, they can make decisions that lead to better long-term, sustainable outcomes.

## Steps to Complete

* Set up the application on QA and production servers (Planned for 10/3)
* Review the application on QA and production servers (Planned for 10/3)
* Migrate field testers from the development server to production
* Communicate the application's launch to patrol officers

## Business Impact to Systems

Our system has read-only access to the RMS, which it uses to pull information from the Crisis Incident Templates.  It runs an hourly query against the database to keep itself updated, and pulls in roughly 10k records on each query.

The query volume stays constant as the number of users scale, and we have tested the hourly queries on our development server with no issues.

The Crisis Response Team plans to add CAD Hazard entries with links to our application for people who have profiles in our app.

## Risk Factors

* Bugs reported by officers
  * Rendering problems in different browsers
  * Incorrect, malformed, or missing data

We have added a form in our application where patrol officers can submit feedback about the app directly to our team. We hope this helps us catch any issues or bugs early.

## Who is Required

Toby Baden is supervising the launch on production and QA servers.

The Crisis Response Team is populating information in the app.

The Code for America team is handling technical problems and bug fixes for the two weeks following launch.

## Communication Plan

Since April, we have communicated our plans for the app to officers in their roll calls.

We have prepared an E-Module with instructions for using the application.

## Rollback Plan

We have a "maintenance mode" notice that we can put up if there are any fatal application errors that require us to take the site down.

For smaller problems, our team and the Crisis Response Team are set up to receive feedback and bug reports via email from users of our app, and to make any necessary changes.

**Comment by c-lliope** [comment]
## Test Plan
- Open application by going to the root URL
  - page should display a login screen
- Sign in
  - page should display a search form and a list of people
- Search by a person's name, date of birth, and race
  - Search results should be pared down appropriately
- Click on a person's card to see their profile
  - Page should show historical information pulled from their Crisis Incident Templates

**Comment by graysonwright** [comment]
This was approved.
