### ISSUE TITLE
Add Sentry for error monitoring

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#296]
See:
- https://hub.docker.com/_/sentry/
- https://docs.sentry.io/clients/ruby/integrations/rails/

**Comment by graysonwright** [comment]
This is mostly a nice-to-have; it's a good safety net to help catch & get to the bottom of production errors.

It seems easy to set up Sentry in a Docker container running alongside the app, which would be compliant with most PII / HIPAA / CJIS requirements.

**Comment by antislice** [comment]
This issue was moved to getridealong/crisisresponse#131
