### ISSUE TITLE
Support SSL for secure connections

### ISSUE THREAD

**Issue by graysonwright** [codeforamerica/crisisresponse#297]
See:
- https://hub.docker.com/r/articulate/http-to-https/

**Comment by graysonwright** [comment]
I've had good results with https://github.com/lgromanowski/letsencrypt-plugin in other projects. I haven't tried it directly for a Docker/Rails app, but it seems like it would work fine.

https://github.com/lgromanowski/letsencrypt-plugin/wiki/Installation-guide

**Comment by antislice** [comment]
This issue was moved to getridealong/crisisresponse#130
