### ISSUE TITLE
Decide deployment strategy

### ISSUE THREAD

**Issue by kbnammacher** [codeforamerica/crisisresponse#9]
- What are the tradeoffs for different deployment options?
  - How does these options compare in time/effort that takes to deploy changes?
  - Compare with maintenance work to keep each of the macbook and SPD laptop up to date?
    - How much work to keep dummy databases up to date?
    - Dependencies on the CentOS server?
- What are the limitations of developing entirely remotely through Docker containers?
- What would it take to set up a comfortable development environment on CentOS?

**Comment by c-lliope** [comment]
At the moment, we have two deployment options:
- Develop on macbook, transfer to server to deploy
  - Positives
    - Use GitHub, CI services more directly in workflow (#11)
    - Familiar dev environment
    - Install dependencies directly 
  - Risks
    - Long time to deploy
    - Dummy database maintenance
- Develop on linux, transfer dependencies from macbook
  - Positives
    - Short deploy time
    - Develop with a direct connection to the database(s)
  - Risks
    - No internet - time & effort to install dependencies (#13)
    - Trickier to manage development environment (#12)
    - More time & work to transfer code to GitHub (#14)
    - Need to run regular backups in case of a disk failure on linux server (#14)

As we create issues to answer these questions, I'll add links from these bullet points.

**Comment by graysonwright** [comment]
Taken care of by #72, #109, #230, #16, etc.

Essentially, we went with Docker.
